# Referenced Google Doc: https://docs.google.com/document/d/1KDtC6QHN6HqJTCUWnPgtxOs-J6uZOJD4CFOg39lgf5Q/edit?usp=sharing

# Notes: Should it be
# BLEH:
#   DEFAULT:
#     TEXT:
#       - None
#     Extra:
#       Emphasis:
#         - Reduced
# OR
# BLEH:
#   DEFAULT:
#     TEXT:
#       - None
#     Extra:
#       - None

# Example
    # config_file = open('app_config.yaml')
    # configuration_contents = yaml.load(config_file, Loader=yaml.FullLoader)
    # print(configuration_contents[0]['VOICE_ID'][0]['DEFAULT'][0]) //RETURNS Jonanna
    # configuration_contents[0]['VOICE_ID'][1]['CONFIG'][0] //RETURNS None

# Documentation
# Each tag is in caps
#   A tag will have two levels
      # - DEFAULT
        # The default tag will be the default settings, if the user hasn't specified their own config, the default will take over
      # - CONFIG
        # This tag is what the user can specify, the program will look for the users configuration first before goint to the default version
    
# Amazon Polly
- VOICE_ID:
  - DEFAULT:
    - Joanna
  - CONFIG:
    - Brian 

# Mathmode
- QUANTITY_MODES:
  - DEFAULT:
    - PARENTHESES_NUMBERED
  - CONFIG:
    - None

- MATHMODE_NO_RENDER:
  - DEFAULT:
    - math not rendered
  - CONFIG:
    - None

# Commands

- FONT:
  - DEFAULT:
    - None 
  - CONFIG: 
    - None

- TEXT_COLOR:
  - DEFAULT:
    - None
  - CONFIG:
    - None

- THEOREM:
  - DEFAULT:
    - None:
  - CONFIG:
    - None

- UNDERLINE:
  - DEFAULT:
    - None
  - CONFIG:
    - None

- BOLD:
  - DEFAULT:
    - Emphasis:
      - Strong
  - CONFIG:
    - None

- ITALICS:
  - DEFAULT:
    - None 
  - CONFIG:
    - None
  
- COMMAND_NO_RENDER:
  - DEFAULT:
    - None 
  - CONFIG:
    - None